drive_train:
  # Publish all joint states 
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position controllers and set up PID: convert joint position controller to effort values
  left_front_wheel_position_controller:
    type: effort_controllers/JointVelocityController
    joint: Left_Front_Wheel_Joint
    pid: {p: 100.0, i: 0.01,  d: 10.0}

  left_bogie_wheel1_position_controller:
    type: effort_controllers/JointVelocityController
    joint: Left_Bogie_Wheel_1_Joint
    pid: {p: 100.0, i: 0.01,  d: 10.0}

  left_bogie_wheel2_position_controller:
    type: effort_controllers/JointVelocityController
    joint: Left_Bogie_Wheel_2_Joint
    pid: {p: 100.0, i: 0.01,  d: 10.0}

  right_front_wheel_position_controller:
    type: effort_controllers/JointVelocityController
    joint: Right_Front_Wheel_Joint
    pid: {p: 100.0, i: 0.01,  d: 10.0}

  right_bogie_wheel1_position_controller:
    type: effort_controllers/JointVelocityController
    joint: Right_Bogie_Wheel_1_Joint
    pid: {p: 100.0, i: 0.01,  d: 10.0}

  right_bogie_wheel2_position_controller:
    type: effort_controllers/JointVelocityController
    joint: Right_Bogie_Wheel_2_Joint
    pid: {p: 100.0, i: 0.01,  d: 10.0}