frequency: 15
sensor_timeout: 0.5
two_d_mode: true
publish_tf: true

# Sensor sources
imu0: /sensors/imu/data
odom0: /localization/navsat/odometry  # odometry/gps is the default name from navsat_transform, but we remapped it to be cleaner.

# These boolean arrays tell the EKF which parts of the sensor message to use 
# when updating its state estimate. Each index in the array corresponds to one 
# element of the state vector, which is typically ordered like this:
# 1. Position: x, y, z
# 2. Orientation: roll, pitch, yaw
# 3. Linear Velocity: x_dot, y_dot, z_dot
# 4. Angular Velocity: roll_dot, pitch_dot, yaw_dot
# 5. (Optional) Acceleration: x_accel, y_accel, z_accel

# IMU confguration; NOTE: We left (3) and (4) unchecked because these may have a tendency to have noise, and other sensors can provide these readings (e.g. wheel/visual odometry).
imu0_config:  [false, false, false,
               true,  true,  true,
               false, false, false,
               true,  true,  true,
               false, false, false]

# GPS configuration
odom0_config: [true,  true,  false,    # x,y only (2D)
              false, false, false,
              false, false, false,
              false, false, false,
              false, false, false]

# Frame settings       
map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: map # The frame in which this EKF publishes the robot's pose.